Makefile: fix "tests_list.h: No such file or directory" error
Error Output:
--------------------
$ make -j4
Building fvp
Selected set of tests: standard
  CC      tftf/framework/aarch64/arch.c
  CC      tftf/framework/debug.c
  CC      tftf/framework/main.c
  CC      tftf/framework/nvm_results_helpers.c
include/lib/aarch64/arch_helpers.h: Assembler messages:
include/lib/aarch64/arch_helpers.h:185: Error: no such instruction: `mrs %rax,CurrentEl'
include/lib/aarch64/arch_helpers.h:295: Error: no such instruction: `msr hcr_el2,%rax'
include/lib/aarch64/arch_helpers.h:214: Error: no such instruction: `isb'
In file included from tftf/framework/nvm_results_helpers.c:10:0:
tftf/framework/include/nvm.h:13:10: fatal error: tests_list.h: No such file or directory
 #include "tests_list.h"
          ^~~~~~~~~~~~~~
--------------------

Workaround:
$ make -j1

There is missing dependency in the Makefile.

Many sources is depending on the tests_list.h (.c) to be generated.
In multi-thread environment:
  Thread 0: run AUTOGEN to build tests_list.h (.c)
  Thread 1: start to build tftf.bin, compile .c file
  Thread 2: start to compile .c file
  Thread 3: start to compile .c file <-- Need tests_list.h
  Thread 4: . . .

So the first time run `make` will hit the problem.
The second `make` will be good, if the tests_list.* is generated
(Thread 0 finished its job).
Then it will hit another dependency problem